### ISSUE TITLE
Case issue and no corresponding word in some translation.

### ISSUE THREAD

**Issue by Nemirtingas** [MycroftAI/skill-speak#18]
When you use cli, if you use an uppercase beginning letter (like Say), then it doesn't get removed in the result.
Say Hi => Say Hi
say Hi => Hi

Also there's a bug in the french translation:
in regex/fr-fr/Words.rx there are only 2 different triggers: 'dis' and 'répète'
dis (?P<Words>.*) <------ Replace this as 'parle'
dis (?P<Words>.*)
répète (?P<Words>.*)

But in vocab/fr-fr/Speak.voc there are 3 of them: 'parle', 'dis', 'répète'
parle
dis
répète

**Comment by forslund** [comment]
Hi @Nemirtingas I'll look over the regexes, as you say they should be case instensitive.

For the missing parle in the french translation feel free to submit this change at https://translate.mycroft.ai
