### ISSUE TITLE
deprecate skill?

### ISSUE THREAD

**Issue by JarbasAl** [MycroftAI/skill-speak#24]
This skill could be replaced by https://github.com/JarbasSkills/skill-parrot

parrot includes PR #8 , solves #6 and adds extra functionality, both skills do basically the same.

In parrot skill i am blacklisting this skill because of issues linked above

Parrot skill very simple and is a good template to show new users the usage of converse method

**Comment by krisgesling** [comment]
At first I wasn't convinced but really this Skill is "repeat what I say" and then there can be two modes, one-off or ongoing parroting. So yeah I feel like it makes sense to incorporate them. 

In terms of how to go about that, it seems like there'll be less messing around to update this Skill than doing a switcheroo to replace a default Skill with another. 

A couple of things:
- We'll want to extend the [Voight Kampff tests](https://github.com/MycroftAI/skill-speak/blob/20.02/test/behave/speak.feature) to cover any new functionality. I've also started adding tests for phrases that a Skill **should not** respond to, which will help with avoiding intent collisions through future changes.
- It seems like we could clean up some of the image files at the top-level directory?
- And in terms of the parrot photos, are all of these available for use under open licenses? We need to be very sure about any content we're hosting and distributing to all devices.

The "repeat recent" Skill also looks like a brilliant addition to the Marketplace as a separate Skill.

**Comment by JarbasAl** [comment]
since this was the first skill ever using the converse method (the one i used to [develop it](https://github.com/JarbasSkills/skill-parrot/commit/9d7934e4def0199e5716e8f00d1d6566fef18751) actually) and it shares basically no code base with the current skill, i would like to retain commit history

i wouldn't mind transferring the skill to mycroft org, either current approach taken by the parrot skill or something like what was done in stock skill would work to avoid skill conflicts

the images will certainly need replacing, they were downloaded with a google search script

**Comment by JarbasAl** [comment]
also note the parrot skill now also includes the "repeat recent" intents, but takes into account message.context
